### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#1318]
- [x] Create Vega Specs with labeling using reactive geometry
- [x] Create vega-lite spec for labels to discuss
- [x] Discuss implementation language of labels

https://gist.github.com/willium/d261c423969e35709714f3f429fb10b9
