### ISSUE TITLE
Labeling - Milestone 2

### ISSUE THREAD

**Issue by willium** [vega/vega-lite#1319]
- [ ] Implement specs for labeling in vega-lite (no occlusion features yet), all marks
  - [ ] Implement anchoring
  - [ ] Implement offset (pythagorean theorem for corners)
  - [ ] Implement basic coloring, auto coloring, (relative coloring --  in layered spec only)
- [ ] Implement default layering based spec, and encoding channel short-hand
- [ ] basic occlusion
- [ ] bounding box and such in Vega

**Comment by willium** [comment]
Currently blocking on layering
