### ISSUE TITLE
Maps - Milestone 1: Projections

### ISSUE THREAD

**Issue by bobocandys** [vega/vega-lite#1322]
- Default projection: Mercator
- Mapping from latitude/longitude to x/y in vega-lite.

**Comment by kanitw** [comment]
- [ ]  Add new type of mark “path” 

- [ ] Add new file `src/compile/data/geo.ts` for geo and geopath transform
  -  [ ] if `mark == 'path'`, then do `geopath` transform else do `geo` transform

Let's revise the TODO more once we are done with input/output

**Comment by kanitw** [comment]
will address as a part of #1423
