### ISSUE TITLE
Redo the layering revision PR

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1602]
In #1304, we did a lot of things. 
We should break down different things that we try to achieve in that PR and list them here, so we can discuss do each of them in more atomic fashion. 
## TODO
- [x] re-order transforms
  - [x] rename data sources
  - [x] NEW Consider where post-aggregation calc and filter would be if we were to implement them.  (Avoid major revision in the future) 
- [ ] When unioning scales, show title of the unioned fields in the axis title.
- [x] Make sure composition works with placeholder data (see #1392)

**Comment by kanitw** [comment]
- [ ] re-order transforms

**Comment by domoritz** [comment]
Steps on the way
- [ ] `domain: "preAggregate`
- [ ] Remove the need for separate raw source for pre aggregated domain by including min/max
- [ ] Add `data: {bind: "A"}` (#1392)

**Comment by kanitw** [comment]
@domoritz When you have time, could you please check if you have achieved everything you wanted to do here.  If so, close the issue.

**Comment by kanitw** [comment]
Hmm, we probably haven't union axis title.

**Comment by kanitw** [comment]
union axis title should be a part of #2251
