### ISSUE TITLE
Important Vega 3 Migration Follow-Up

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1665]
- [x] ~~The `rule` mark type now supports arbitrary line segments, and reliably draws a line from point `"x"`, `"y"` to point `"x2"`, `"y2"`.~~ (#1801)

- [ ] rename all `<marktype>.properties()` to ``<marktype>.encodeEntry()` that return `VgEncodeEntry` type. 

- [x] rename all `scaleConfig.*ColorRange` to  `scaleConfig.*ColorScheme`

-  The `"band"` property now accepts an interpolation fraction between 0 and 1 for placing elements within a scale band, and can now be used in conjunction with a field-based scale mapping. For example, the following encoding places an item at the midpoint of the appropriate scale band: `{"scale": "xscale", "field": "foo", "band": 0.5}`.
    - [ ] ~~Should we allow specifying this in some way?~~

- [x] `zindex` is `0` by default in Vega.  Currently in Vega-Lite the default is 1 except when grid is true. We should revise this default.

- [x] ~~x and y do not really support arbitrary band scale yet~~ (Done in #1691)

- [ ] scale.interpolate

- [ ] mark's interpolate

- [ ] config.mark.filled

# VL Syntax
- [x] axis/legend.properties => axis/legend.encode (or remove it?) 

# Docs
- [ ] scale type

**Comment by kanitw** [comment]
- [ ] bin transform no longer output bin_mid by default.  For now, I **always** add a formula transform to calculate the bin_mid but we could handle this better.

**Comment by kanitw** [comment]
Follow up for #1689 

- [ ] `domain` => `parseDomain`
- [ ] correct place `useRawDomain` without hack
- [ ] move range to initScale and consolidate initScale with initSize + #1647

**Comment by kanitw** [comment]
Splitted into multiple issues.
