### ISSUE TITLE
Use `zindex` for layer `order` channel instead 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1684]
Currently we use sort transform to determine layer order for `order` channel. 
In Vega 3, we can consider using `zindex` property instead.

**Comment by kanitw** [comment]
Maybe we just add `zindex` or `layer` as its own channel?  

This might allow us to make `order` means either path order or stack order and free up `path` channel for Geo stuff.

**Comment by jheer** [comment]
In case this effects your reasoning (it may not, but just to be safe): `zindex` is used only for sorting **sibling nodes** in the scenegraph tree. If `zindex` is set on individual items, it will have no effect on the ordering relationship between items that are children of different marks.

**Comment by kanitw** [comment]
Since zindex expects non-negative integer, looks like we have to apply rank transform to determine range of zindex scale.

**Comment by kanitw** [comment]
# TODOs

- [ ]  Try modifying Vega manually
  - [ ] add scale for `zindex` based on origin. 
  - [ ] How can we automatically determine range for `zindex`'s scale 
  - [ ] Add `zindex` to mark's `encode` using the scale above. 

- [ ] Modify the code
  - [ ] deal with the range for zindex scale
  - [ ] Add zindex following the typical steps for adding channel in #1278

**Comment by kanitw** [comment]
> How can we automatically determine range for zindex's scale

If we really need to do this, we might want to add this as a part of the layout data source rather than adding a new data source.

**Comment by kanitw** [comment]
Since this is (1) complicated and (2) doesn't seem that useful anyway.  Let's not include `zindex` in VL2.  Whenever users need to re-order zindex their marks, it's a sign of overplotting anyway.

**Comment by arvind** [comment]
`zindex` support would be helpful for interactive use-cases to pull selected points to the foreground:

z-index-less: partially occluded points can be selected, but then are only partially visible.
![untitled](https://cloud.githubusercontent.com/assets/42262/23317361/ec4e4c18-fa82-11e6-86a9-60ec0faa16a2.gif)

with a simple z-index definition (in Vega)
![untitled2](https://cloud.githubusercontent.com/assets/42262/23317362/ed81383e-fa82-11e6-9b2d-438f6abc93be.gif)

**Comment by kanitw** [comment]
Actually, one quick question --- do we always want this behavior for selected point?  
If so, we could add zindex to the output Vega without adding new encoding channel in Vega too.

(Or even if we don't, we make this a config.)

**Comment by arvind** [comment]
Good question. I thought about it but wasn't able to think of `zindex` outputs that would generalize across selection designs (e.g., what if you wanted to highlight points _not in_ the selection, then the selected points should have a lower `zindex`; what to do with multiple selections per unit spec, etc.)

**Comment by kanitw** [comment]
@arvind Do we still need this for 2.0 -- if not, we can move to Milestone 2.1?

**Comment by arvind** [comment]
Not required for 2.0. I switched the `query_widgets` example (shown above) to explicitly use layers with #2464.

**Comment by kanitw** [comment]
Note that I just make `order` for non-stack, non-line marks affect the underlying Vega mark's `sort` property, which also affect the other.  However, z-index may still be useful for the use case [above](https://github.com/vega/vega-lite/issues/1684#issuecomment-282379770).

**Comment by domoritz** [comment]
Why can we not use order for the case above? You could set the order to be a special value if it's in the selection.

**Comment by kanitw** [comment]
Order right now is designed to be mapped to mark `sort`, not `zindex` so it doesn't support ValueDef.  

Also, even if we add special case to map "value" `order` to zindex, `order` still won't work with line's zindex as for line, order mean order of points in the line.

**Comment by cogpie** [comment]
Just to add another voice to a request in this space. Ran into the same issue as @arvind above, although somewhat worse as the data is categorical on both axes. It could be I am doing visualisation all wrong, but in this context I have selected points hidden behind others on top.

**Comment by domoritz** [comment]
You can also create a second layer with just the filtered data.

**Comment by kanitw** [comment]
This is a duplicate of https://github.com/vega/vega-lite/issues/4864, which is now fixed.
