### ISSUE TITLE
Incorrect Color for Ordinal Fields

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#1732]
From https://github.com/altair-viz/altair/issues/245, using ordinal fields with ordinal color seems to be incorrect.

**Comment by kanitw** [comment]
Using "ordinal" without custom domain doesn't produce the right order for color scale. 

```
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"}, {"a": "B","b": 55, "c": "small"}, {"a": "C","b": 43, "c": "x-large"}, {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "ordinal"}
  }
}
```

![vega_editor](https://cloud.githubusercontent.com/assets/111269/20691378/6043c1ea-b585-11e6-8c96-dd3a8f9e17bd.png)

Thus, we should add custom domain. 
```
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"}, {"a": "B","b": 55, "c": "small"}, {"a": "C","b": 43, "c": "x-large"}, {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "ordinal", "scale": {"domain": ["x-small", "small", "large", "x-large"]}}
  }
}
```

However, this  causes two problems:

1) It makes the output color all black since we use `linear` color scale for ordinal data by default. 
2) The custom domain has no effect, probably due to the `color_legend` we have to produce.

![vega_editor](https://cloud.githubusercontent.com/assets/111269/20691400/8d4022d8-b585-11e6-8ed9-3892cdf3ce77.png)

```
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"}, {"a": "B","b": 55, "c": "small"}, {"a": "C","b": 43, "c": "x-large"}, {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "ordinal", "scale": {"type": "ordinal", "domain": ["x-small", "small", "large", "x-large"]}}
  }
}
```

Making the scale type = `ordinal` makes the color show, but still incorrectly. (Alternating between start and end color)

![vega_editor](https://cloud.githubusercontent.com/assets/111269/20691632/1129ae88-b587-11e6-9e54-70f0cb217450.png)

Providing custom range (e.g., GnBl from color brewer) now gives nice output, but still in a wrong order.

```
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"}, {"a": "B","b": 55, "c": "small"}, {"a": "C","b": 43, "c": "x-large"}, {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "ordinal", "scale": {"type": "ordinal", "domain": ["x-small", "small", "large", "x-large"], "range": ["#f0f9e8","#bae4bc","#7bccc4","#2b8cbe"]}}
  }
}
```

![vega_editor](https://cloud.githubusercontent.com/assets/111269/20691757/fec4338e-b587-11e6-83a1-bb0c324d6abb.png)

## Temporary Workaround

For now, setting data type to `nominal` avoid the problem (as nominal field does not produce the `color_legend` scale in Vega like ordinal).  We also do not have to set scale type to `ordinal` manually.   

```
{
  "data": {
    "values": [
      {"a": "A","b": 28, "c": "x-small"}, {"a": "B","b": 55, "c": "small"}, {"a": "C","b": 43, "c": "x-large"}, {"a": "D","b": 13, "c": "large"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "type": "nominal", "scale": {"domain": ["x-small", "small", "large", "x-large"], "range": ["#f0f9e8","#bae4bc","#7bccc4","#2b8cbe"]}}
  }
}
```

![vega_editor](https://cloud.githubusercontent.com/assets/111269/20691858/cb6ec502-b588-11e6-87d9-342db6b65416.png)

## TODO

- [ ] a) Check if linear or sequential scale in Vega 3 already produces correct output in this case.  (Probably not, but worth checking)

- [ ] b) If a) is not true, it seems like the new `index` scale in Vega 3 is created specifically for this purpose.
  
- [ ] c) If `index` scale also doesn't work, we can also consider 
  - c1)
    - [ ] Use ordinal "lookup" scale for color of ordinal field if custom domain is provided
    - [ ] Manually Interpolate the output color range
  - c2)
    - [ ] Pass the input ordinal data through rank transform. 

IMHO, we should avoid c1 and c2 unless it is necessary.  

(@domoritz, I'm assigning this to you since I guess you'll be the one who handles color scale migration to Vega 3.)

**Comment by dhimmel** [comment]
Here's another example of the issue that I mentioned in https://github.com/altair-viz/altair/issues/245#issuecomment-263419044:

```json
{
  "data": {
    "url": "https://raw.githubusercontent.com/dhimmel/biorxiv-licenses/4ad9659e4fc823f4c491e13be4505248df5c1ab6/figure/license-vs-time/vega-lite-data.json"
  },
  "config": {
    "mark": {
      "stacked": "normalize"
    }
  },
  "encoding": {
    "color": {
      "field": "license",
      "scale": {
        "domain": [
          "CC BY",
          "CC BY-ND",
          "CC BY-NC",
          "CC BY-NC-ND",
          "None"
        ],
        "type": "ordinal"
      },
      "type": "nominal"
    },
    "x": {
      "axis": {
        "axisWidth": 0.0,
        "format": "%Y",
        "labelAngle": 0.0,
        "tickSize": 0.0
      },
      "field": "date",
      "scale": {
        "nice": "month"
      },
      "timeUnit": "yearmonth",
      "title": " ",
      "type": "temporal"
    },
    "y": {
      "aggregate": "count",
      "axis": {
        "axisWidth": 0.0,
        "grid": false,
        "labels": false,
        "ticks": 0.0
      },
      "field": "*",
      "title": "Proportion of Preprints",
      "type": "quantitative"
    }
  },
  "mark": "area"
}
```

Notice how the legend ordering doesn't match the ordering of the normalized area marks.

![vega](https://cloud.githubusercontent.com/assets/1117703/20693613/91366726-b5ad-11e6-9f33-d0e6e7c5c2fe.png)

**Comment by kanitw** [comment]
@dhimmel  Thanks for reporting. That's actually a slightly different issue, so I created #1734 for this. :)

**Comment by domoritz** [comment]
Index scales should work for specifically this purpose. This means we will support it in Vega-Lite 2.0 because we need Vega 3 scales. 

There seem to be a few issues with index scales that need to be resolved first https://github.com/vega/vega/issues/667

**Comment by kanitw** [comment]
Addressed in #1746 (pending review)
