### ISSUE TITLE
Add bin, aggregate, timeUnit to the transform array

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2344]
The `transform` array should support the following transforms:

- `BinTransform`

```json
{
  "bin": true, "field": "acceleration", "as": "binned_acceleration"
}
```

- `TimeUnitTransform`

```json
{
  "timeUnit": "year", "field": "date", "as": "year_date"
}
```

- `AggregateTransform`

```json
{
  "summarize": [
    {"aggregate": "sum", "field": "acceleration", "as": "sum_acceleration"},
    {"aggregate": "mean", "field": "horsepower", "as": "mean_horsepower"}
  ],
  "groupby": ["origin", "cylinders"]
}
```

## TODO 

- [ ] Add these interfaces to `transform.ts`
- [ ] Modify `parseTransformArray` in `src/compile/data/transforms.ts`
All of these transforms should be able to reuse existing `Bin/TimeUnit/AggregateNode` in the transform pipeline. 

- [ ] Add a test example where we calculate / filter based on aggregate value
  - [ ] Create a "full" example of boxplot with 1.5 IQR whiskers
