### ISSUE TITLE
Chart Composition (Multiple X,Y s – layering / juxtaposition)

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#24]
## Common Refactor

- [ ] distinguish between general model and a `Single` unit model
  - General model: produces scale, axis, legends
  - Single unit model: produces marks (and possibly others)
- [ ] layout
- [ ] data
- __facet__
  - [ ] re-compile `row` and `column` to use `facet`
  - [ ] rewrite `facet.ts` 

## Sub-issues

- layering #585 
- multiple x,y on the same axis
- dual axes

**Comment by kanitw** [comment]
@ellisonbg @domoritz Let's continue the conversation from #539 here.

One challenging in terms of specification design here is whether we have to adjust how we specify axis and scales given that there will be some properties shared across layered axes.  (and sometimes you want them to be different) 

That said, there are a lot of refactoring tasks that I would like to do before introducing major feature like this.

**Comment by ellisonbg** [comment]
OK, I will watch this to see when this stuff starts to move forward. Thanks!

On Wed, Aug 5, 2015 at 7:23 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> @domoritz
> <https://github.com/domoritz> Let's continue the conversation from #539
> <https://github.com/uwdata/vega-lite/issues/539> here.
>
> One challenging in terms of specification design here is whether we have
> to adjust how we specify axis and scales given that there will be some
> properties shared across layered axes. (and sometimes you want them to be
> different)
>
> That said, there are a lot of refactoring tasks that I would like to do
> before introducing major feature like this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwdata/vega-lite/issues/24#issuecomment-128216290>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
@ellisonbg   We sketched some syntax for composition in this docs.  
Note that the docs isn't perfectly cleaned because I wrote it to explain to people in person, but you probably get an idea about what we are thinking  https://docs.google.com/document/d/1moMVll7p-gFj4l9lYY1fejpr5zqY4iK045HeXgPB9bk/edit#

If you have questions, please feel free to comment or we could do a video call as well.

**Comment by ellisonbg** [comment]
Great I will have a look!

On Fri, Feb 26, 2016 at 9:18 AM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> We sketched some syntax for
> composition in this docs.
>
> Note that the docs isn't perfectly cleaned because I wrote it to explain
> to people in person, but you probably get an idea about what we are
> thinking
> https://docs.google.com/document/d/1moMVll7p-gFj4l9lYY1fejpr5zqY4iK045HeXgPB9bk/edit#
>
> If you have questions, please feel free to comment or we could do a video
> call as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vega/vega-lite/issues/24#issuecomment-189379114>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by kanitw** [comment]
Closing this issue since it's basically describe the milestone that has many sub-issues.
