### ISSUE TITLE
Selection Docs Revision

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2693]
Known issues:
* [x] Brushes do not always track the mouse cursor (#2695). Fixed with vega/vega-view#13, pending a Vega release + deployment.
* [x] Points overflow on the scale binding and translate docs (will be resolved by #2692).
* [x] Composing/resolving brushes do not work correctly when brushes have been cleared (#2696).

**Comment by ZeningQu** [comment]
![highlight](https://user-images.githubusercontent.com/822034/28436199-e9165b90-6d4a-11e7-9a66-9ef851206c92.gif)

I really like that you can play with the examples in the doc page itself. Just have an non-urgent thought that if you could highlight the changing parts in the spec (or highlight the relevant fields in the spec) it would make the doc even easier to read.

**Comment by kanitw** [comment]
- [ ] Missing abstract code block at the top (to help locate the selection property) -- See top of data, transform, mark pages for example
  - [ ] This abstract code block should also make it clear that selection is a dictionary that maps names of the selections to their definitions.  (The property table up top does not make it clear that this is only the defintion part, not the name. -- This later becomes clear in an example, but we could make it a bit clearer up front.)

**Comment by kanitw** [comment]
- [ ] `mark` property is only listed in a paragraph, but not in the table on the top.

**Comment by kanitw** [comment]
- [ ] There is no reference from the part about `mark` to corresponding selection config section. 
- [ ] Actually, there is no docs for selection config yet.   

Related Note: we should discuss whether we want to distribute content for different kinds of configs into their related page or put all of them in config.html.  Right now, axis and legend configs are in axis/legend page but other configs are in still config.html.  I'm leaning toward splitting them and add link from config.html; otherwise this page will be insanely long.

**Comment by kanitw** [comment]
- [ ] Transform page missing a section about selection filter (which could either contain similar example to the selection or be very brief and link to selection page)

- [ ] `domain` in the scale page does not discuss about domain binding yet (Need to add brief description + a link to selection page to scale.ts and re-compile schema)
