### ISSUE TITLE
Limit facet to only have layer or unit inside

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#2760]
The semantic of facet would not be what people expect. 

(I'll provide more example soon)

**Comment by domoritz** [comment]
I feel having a repeat could be a useful thing to have inside a facet. Admittedly, you could do the inverse: a repeat of a facet. Anyway, I would like to see some examples of how the output is unexpected and an argument that there aren't cases where you would want arbitrary composition.

**Comment by kanitw** [comment]
I think Repeat of facet is way better visualization than facet of repeat as
the latter would be extremely confusing for readers (non-creator).

**Comment by arvind** [comment]
A while ago, I had created a facet of concat plots to see two different views of each facet.

**Comment by kanitw** [comment]
I think longer term we certainly should support all of them. 

However, currently there are some amount of corner cases that we do not support well. 

- [ ] https://github.com/vega/vega-lite/issues/2759 -- facet of concat of facet_column (I haven't test if it works, but suspect that it probably won't.) 

- [ ] https://github.com/vega/vega-lite/issues/2775 Cross Nested Facet

So instead of delaying our release more, I'd rather support less things, but do them well.

**Comment by kanitw** [comment]
In #2977, we now limit facet to only have layer or unit inside.  I'm changing this issue to become "Support generic spec inside facet" and move it out from 2.0 milestone.

**Comment by domoritz** [comment]
- [ ] Support faceted concat https://github.com/vega/vega-lite/issues/5261

**Comment by kanitw** [comment]
Here is a cool example of facet concat use case: https://observablehq.com/@datadesk/california-covid-19-disparities-stacked-bars.
