### ISSUE TITLE
Support UTC Time

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#446]
- [ ] UTC TimeUnit
- [ ] UTC Scale
  - Add `utc` to the schema and the docs
- [ ] UTC DateTime Object
  - Simply add `utc: boolean` property 
- [ ] Add an example in `scale.md` that uses utc scale.

**Comment by kanitw** [comment]
@domoritz  -- not sure if this is on your radar, but it seems relevant to the stuff that you're doing.

**Comment by domoritz** [comment]
We should not use UTC for the output because dates are parsed using the current time zone. When we add a way to parse dates as UTC, then we should also output them as UTC.

**Comment by domoritz** [comment]
Right now, nothing is parsed or shown in UTC. 

We should add an option to parse and view in UTC but it's not urgent so I'll leave this.

**Comment by kanitw** [comment]
If I understand correctly, you fixed the make the local time stuff working correctly, so the only stuff left is to support UTC as well?

**Comment by domoritz** [comment]
Yes. Modulo some weird js behavior. See https://github.com/vega/datalib/issues/63

**Comment by kanitw** [comment]
Renamed to "Support UTC Time and updated the description above"

**Comment by peller** [comment]
Seems like a major usability issue. Could this be as simple as offering the user a switch and using the `.utc` time scales in d3?

**Comment by kanitw** [comment]
Actually I just checked, you can use `utc` as a scale type too, we just haven't updated the docs.

**Comment by domoritz** [comment]
> Actually I just checked, you can use utc as a scale type too, we just haven't updated the docs.

It's more than that. We also have to make sure that all the `timeUnit` stuff works with utc.

**Comment by peller** [comment]
> Actually I just checked, you can use utc as a scale type too, we just haven't updated the docs.

[Like this](https://jsfiddle.net/p93coymL/)?  I'm getting strange results for the X axis.  Not sure if this is what @domoritz meant.

**Comment by domoritz** [comment]
Yeah, like that. We simply haven't tested it properly. UTC is a new feature that is currently not supported but implementing it should only require a few adjustments.

**Comment by kanitw** [comment]
Yeah, that's mainly why we haven't added it in http://vega.github.io/vega-lite/docs/scale.html#type yet

**Comment by kanitw** [comment]
> We should add an option to parse and view in UTC but it's not urgent so I'll leave this.

Is there really an easy way to parse things in UTC? AFAIK the parse behavior depends on the input data and the specified parse format.  

In any case, I think the option to output UTC correctly is extremely crucial.

**Comment by kanitw** [comment]
@domoritz  Did you have some branch that started on UTC already?

**Comment by domoritz** [comment]
no

**Comment by kanitw** [comment]
This issue seems relevant: https://github.com/vega/vega/issues/741

**Comment by YuhanLu** [comment]
From the discussion with @kanitw, we try to analyze the design space related to UTC, which involves both input and output.

## INPUT

There are two cases: 
1) `format："auto"`.  Normally it parses date in local time, but if the data follows ISO format, it parses data in UTC (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse).

2) custom `format`: 
- local time    use `"date:format"`
utc time       use `"utc:format"`


## OUTPUT

From preliminary exploration, Zoe thinks that:

1) If the input is already read as UTC, using normal time scale and normal time expression for timeUnit, would show UTC values. 

- [ ] verify with date that you know timestamp 
- [ ] After verifying, think if we need custom offset at all.  (Ham: probably not, users likely just need to customize the format, between `utc:...` and `date: ...`.

2) If the input is read as local time, users may wanna use utc scale and utc time expression for timeUnit to show UTC values. 

## TODO
- [ ] test how Vega stores date (Date object or just timestamp)
  - [ ] If it's a timestamp, you might want to construct a dataset that contains data at a particular timestamp (e.g., `0`)

- [ ] Create an example data where time/utc scale type matters 
- [ ] Verify that when we use utc prefix for timeUnit expression, we should always use scaleType=“utc"

## SYNTAX 

A few alternatives to let VL correctly add “utc” prefix to timeUnit:

- [ ] add utc prefix to timeUnit e.g., “yearmonth” => “utcyearmonth”   for not timeUnit => “utc"
- [ ] scaleType==‘utc’ - then add utc prefix to everything

We definitely need the latter. Then should the former be automatically inferred from the scale type or do we include it as a part of timeUnit but throw an error for inconsistent state (if it needs to be consistent.)
