### ISSUE TITLE
Vega 2 migration basics

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#459]
- [x] use the new `name` mark property in groups

### Field 

- [x] remove `.data` direct access — use `fieldRef` instead
- [x] remove `.data` from `field` 
- [x] `index` => `_id` in `field`

- [x] replaced mark’s `group` property with `field.group` #593

### Scale

- [x] use scale’s sort for sorting (Done in #612)

### Transform

- [x] stats => aggregate (Done in #604)

- Facet
  - [x] `keys` => `groupby` (Done in #604)
  - [x] Eliminate `keys.0` reference

- [x] Stack #412

- [x] Check if we use any of removed transforms: array, copy, flatten, slice, truncate, unique, window (__We did not__)

- [x] Table Heatmap

- [ ] ~~Valid test cases against Vega 2 JSON Schema~~ (forked to #613)

**Comment by mprudhom** [comment]
I noticed this issue became unassigned yesterday. I can do some work on it if it would be helpful.

The Vega 2 JSON schema will be useful for validating that the compiled specs are correct.

**Comment by kanitw** [comment]
@mprudhom  Umm it’s actually not truly “unassigned".  I didn’t expect people tracking our issues assignment so I just unassigned this so that I can track stuff I want to do in the next 2 weeks on https://github.com/issues/assigned.

I plan to do this in August.  Since it might will be a large PR that affects other apps downstream, I prefer to do it myself.  But yes, we plan to use vega2 JSON schema to validate output.  

If you have some times to help, we actually listed a number of issues in [Vega-lite](https://github.com/uwdata/vega-lite/labels/help-wanted) and [Polestar](https://github.com/uwdata/polestar/labels/help%20wanted) as “help-wanted”.  So you might want to take a look at some of those and send us PRs.
