### ISSUE TITLE
Parameters/Signals: for Localization and Color Theming

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#5824]
We should have an easy way to enable parameterization for localization and theming (e.g., dark/light mode.)

The best way to support that is to expose signals to certain degree in Vega-Lite.  I know we push back against supporting signals in VL for a long time, but now that it's a part of Vega config, it seems sensible to expose them directly rather than introducing some parameter directive. 

In addition, it will allow us to bind parameters to Vega-Lite examples and immensely improve documentation.  So I think the benefits of simplifying its learning outweighs the cost of learning one more primitive.

# TODO

- Support referring to signals in various places
  - [x] mark properties
  - [x] encoding
  - [x] font size 
  - [x] axis color and title properties
  - [x] legend color and title properties

- [ ] ~~Support declaration of signals~~ -- #5993 
  - We may limit the power of the signals in Vega-Lite.  For example, we may not include `on`.  

- [x] Perhaps, support `config.color` which will output a version of config that replace default color configs specified in `vega-parser`. 

- Lower priority places to support signals
  - [x] scales
  - [x] header properties (can be set via style config)
  - [x] title properties (can be set via style config)
  - [x] projections
  - [ ] transforms
    - [x] calculate and filter might have higher priority
  - [ ] field properties
  - [ ] date time object
  - [ ] width/height/x2Offset/y2Offset (https://github.com/vega/vega-lite/issues/5977)
  - [ ] axis.labelAngle

**Comment by knakul853** [comment]
@kanitw  hey I want to work on this?

**Comment by domoritz** [comment]
@knakul853 We are actually working on this now. Maybe instead you could take an issue from https://github.com/vega/vega-lite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Help+wanted+%3Apray%3A%22?

**Comment by kanitw** [comment]
We pretty much have support for this, let's open another issue to discuss whether we should make this an official feature.
