### ISSUE TITLE
Revise Config

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#666]
- [x] add top-level’s `name`, `padding`, `background`, `description`, `scene`

- leave as top-level as-is: 
  - `sortLineBy`, `stack`
  

- Group things so we can easy map values to vega and help organize config UI for polestar / voyager 
  - `cell`
    - [x]  `background` (formerly `cellBackgroundColor`),  `gridColor`, `gridOffset`,  `gridOpacity`, `padding`, `width`, `height` and other group mark’s properties 
  - `marks`: 
    - [x] `filled` (formerly `encoding.shape.filled`) 
    - [x] opacity (formerly `encoding.color.opacity`) 
    - [x] move all text properties that are currently in `encoding.text`
    - [x] support other non-channel properties (#730) except `shapeOpacity` and `filledOpacity` (users should simply use `opacity`) 
      - [x] text’s dx, dy, radius, theta, angle 
    - [x] `strokeWidth`
  
- remove 
  - [x] `useRawDomain`, `padding`, `bandWidth` — just set default value in scale rather than having two configs. 
  - [x] `gridColor`, `gridOpacity` (unused)
  - [x] `singleHeight`, `singleWidth` — simply always use `cell.width|height`
- need further revision before deciding what to do 
  - [x] ~~`numberFormat`, `timeFormat`~~ has its own #497
  - [ ] ~~filterNull~~ has its own #597
  - [x] `singleBarOffset`
  - [x] `characterWidth`  — move to axis

**Comment by domoritz** [comment]
Let's rename `shapeFilled` to just `filled` because otherwise there is confusion with the shape channel.

**Comment by kanitw** [comment]
- [ ] `config.marks` => `config.mark` ? 

(To be consistent with `config.cell`, which is singular)

**Comment by kanitw** [comment]
- [ ] @domoritz How should we name `cell.gridColor|opacity` – should it still be called `grid` because we actually implement it using rules marks.  But semantically it’s not a rule either.

**Comment by domoritz** [comment]
Let's use the term grid. It doesn't matter how we implemented it.
