### ISSUE TITLE
Draw x,y grid inside facet

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite#920]
Current faceted charts have shared grid across multiple like this:

<img width="878" alt="vega_editor" src="https://cloud.githubusercontent.com/assets/111269/12278199/8fddfe14-b934-11e5-9306-c0c67598c8f8.png">

However, having separate grid for different singles like an example below is nicer.

![](http://www.randalolson.com/wp-content/uploads/usa-vs-japan-fertility-rates-small-multiple-subset.png)

——

## TODO
- [ ] add a property for `split` axis mode (Need to think what should be the name though)
  - In this mode
    - [ ] hide grid from the outside shared x/y axis
    - [ ] add inner x/y axis (inside each cell group) that shows only grid 
    - [ ] decide which properties get applied to the outer axis (e.g., ticks)

**Comment by kanitw** [comment]
@domoritz  The tricky part is that when we do this, we will have two instances of `axis` declaration and thus need a way to customize their property.  (The current single instance `fieldDef.axis` would not work.)

**Comment by kanitw** [comment]
From discussion with @domoritz,  we can says that ticks, etc apply to the outer axis and grid, etc apply to the inner axes (which only show grid).

**Comment by kanitw** [comment]
Related to https://github.com/vega/vega-lite/issues/90
